defmodule CodexPooler.Dev.Seeds.Perf do
  @moduledoc false

  import Ecto.Query

  alias CodexPooler.Accounting.{LedgerEntry, Request}
  alias CodexPooler.Accounts.{Scope, User}
  alias CodexPooler.Catalog.Model
  alias CodexPooler.Gateway.Persistence.{CodexSession, RoutingCircuitState}
  alias CodexPooler.InstanceSettings
  alias CodexPooler.Pools.Pool
  alias CodexPooler.Repo
  alias CodexPooler.Upstreams
  alias CodexPooler.Upstreams.Quota.AccountQuotaWindow
  alias CodexPooler.Upstreams.Schemas.{PoolUpstreamAssignment, UpstreamIdentity}

  @typep quota_window_spec :: %{
           required(:window_kind) => String.t(),
           required(:window_minutes) => pos_integer(),
           required(:quota_key) => String.t(),
           required(:active_limit) => non_neg_integer(),
           required(:credits) => non_neg_integer() | nil,
           required(:used_percent) => String.t() | nil,
           required(:freshness_state) => String.t()
         }

  @perf_seed_key "codex_pooler_perf_seed"
  @seed_key @perf_seed_key
  @perf_pool_slug "dev-perf-pool"
  @perf_http_url "http://127.0.0.1:4058"
  @perf_websocket_url "ws://127.0.0.1:4058/ws"
  @perf_cluster_host "gateway-perf-fake-upstream.codex-pooler-perf.svc.cluster.local"
  @perf_cluster_http_url "http://#{@perf_cluster_host}:4058"
  @perf_cluster_websocket_url "ws://#{@perf_cluster_host}:4058/ws"
  @perf_bootstrap_dir "tmp/gateway-perf/bootstrap"
  @perf_env_path Path.join(@perf_bootstrap_dir, "perf.env")
  @perf_summary_path Path.join(@perf_bootstrap_dir, "seed-summary.json")
  @perf_model_ids ["gpt-5.4-mini", "gpt-5.4", "gpt-5.5"]

  @spec run(%{required(:owner) => User.t()}) :: map()
  def run(%{owner: owner}) do
    reset_perf_fake_data!()

    pool = seed_pool!(owner, %{slug: @perf_pool_slug, name: "Dev Performance Pool"})
    api_key_result = seed_perf_api_key!(owner, pool)
    identities = seed_perf_identities!(owner)
    assignments = seed_perf_assignments!(owner, pool, identities)
    models = seed_perf_models!(pool, assignments)
    quota_windows = seed_perf_quota_windows!(identities)
    circuit_states = seed_perf_circuit_states!(pool, assignments)
    sessions = seed_perf_sessions!(pool, api_key_result.api_key, assignments)
    metrics_token = generate_bootstrap_secret("metrics")
    settings = seed_perf_metrics_token!(metrics_token)

    starter_rows = %{
      "quota_windows" => length(quota_windows),
      "routing_circuit_states" => length(circuit_states),
      "codex_sessions" => length(sessions)
    }

    write_perf_bootstrap!(%{
      pool: pool,
      api_key: api_key_result.api_key,
      raw_api_key: api_key_result.raw_key,
      metrics_token: metrics_token,
      assignments: assignments,
      starter_rows: starter_rows
    })

    %{
      pool: pool,
      api_key: api_key_result.api_key,
      upstream_identities: identities,
      assignments: assignments,
      models: models,
      quota_windows: quota_windows,
      circuit_states: circuit_states,
      sessions: sessions,
      metrics_settings: settings,
      bootstrap_dir: @perf_bootstrap_dir,
      starter_rows: starter_rows
    }
  end

  defp reset_perf_fake_data! do
    perf_pool_ids = from(pool in Pool, where: pool.slug == @perf_pool_slug, select: pool.id)

    Repo.delete_all(
      from ledger_entry in LedgerEntry, where: ledger_entry.pool_id in subquery(perf_pool_ids)
    )

    Repo.delete_all(from request in Request, where: request.pool_id in subquery(perf_pool_ids))
    Repo.delete_all(from pool in Pool, where: pool.slug == @perf_pool_slug)

    Repo.delete_all(
      from identity in UpstreamIdentity,
        where: fragment("?->>?", identity.metadata, "dev_seed") == ^@perf_seed_key
    )
  end

  defp seed_pool!(owner, attrs) do
    timestamp = now()

    %Pool{}
    |> Pool.changeset(%{
      slug: attrs.slug,
      name: attrs.name,
      status: Map.get(attrs, :status, "active"),
      disabled_at: Map.get(attrs, :disabled_at),
      created_by_user_id: owner.id,
      created_at: timestamp,
      updated_at: timestamp
    })
    |> Repo.insert!()
  end

  defp create_api_key_result!(scope, pool, display_name, metadata) do
    {:ok, result} =
      CodexPooler.Access.create_api_key(scope, pool, %{
        display_name: display_name,
        metadata: Map.put(metadata, :operator_notes, "Generated by local dev seeds")
      })

    result
  end

  defp seed_perf_api_key!(owner, pool) do
    scope = Scope.for_user(owner, ["instance_owner"])

    create_api_key_result!(scope, pool, "Dev perf key", %{
      labels: ["dev", "perf"],
      dev_seed: @perf_seed_key
    })
  end

  defp seed_perf_identities!(owner) do
    1..12
    |> Enum.map(fn index ->
      label = perf_upstream_label(index)

      identity =
        %UpstreamIdentity{}
        |> UpstreamIdentity.changeset(%{
          chatgpt_account_id: "dev-perf-acct-#{pad2(index)}",
          account_label: label,
          onboarding_method: "import",
          status: "active",
          plan_family: "perf",
          plan_label: "Performance Fake",
          auth_fresh_at: minutes_ago(2),
          auth_verified_at: minutes_ago(2),
          headers_profile_version: 1,
          last_successful_sync_at: minutes_ago(1),
          created_by_user_id: owner.id,
          created_at: now(),
          updated_at: now(),
          metadata: perf_endpoint_metadata(label)
        })
        |> Repo.insert!()

      store_perf_upstream_credential!(identity, index)

      identity
    end)
  end

  defp store_perf_upstream_credential!(identity, index) do
    {:ok, _secret} =
      Upstreams.store_encrypted_secret(identity, %{
        secret_kind: "access_token",
        plaintext: "dev-perf-upstream-access-#{pad2(index)}"
      })

    :ok
  end

  defp seed_perf_assignments!(owner, pool, identities) do
    identities
    |> Enum.map(fn identity ->
      %PoolUpstreamAssignment{}
      |> PoolUpstreamAssignment.changeset(%{
        pool_id: pool.id,
        upstream_identity_id: identity.id,
        assignment_label: identity.account_label,
        status: "active",
        health_status: "active",
        eligibility_status: "eligible",
        last_healthcheck_at: minutes_ago(1),
        last_successful_sync_at: minutes_ago(1),
        created_by_user_id: owner.id,
        created_at: now(),
        updated_at: now(),
        metadata: perf_endpoint_metadata(identity.account_label)
      })
      |> Repo.insert!()
    end)
  end

  defp seed_perf_models!(pool, assignments) do
    source_assignment_ids = Enum.map(assignments, & &1.id)

    source_assignment_models =
      Map.new(assignments, fn assignment ->
        {assignment.id,
         %{
           "capabilities" => %{
             "responses" => true,
             "streaming" => true,
             "tools" => true,
             "reasoning" => true,
             "image_input" => true
           },
           "service_tiers" => ["default", "priority"],
           "additional_speed_tiers" => []
         }}
      end)

    @perf_model_ids
    |> Enum.map(fn model_id ->
      %Model{}
      |> Model.changeset(%{
        pool_id: pool.id,
        upstream_model_id: model_id,
        exposed_model_id: model_id,
        display_name: String.upcase(model_id),
        status: "active",
        supports_responses: true,
        supports_streaming: true,
        supports_tools: true,
        supports_reasoning: true,
        source_assignment_count: length(assignments),
        first_seen_at: minutes_ago(10),
        last_seen_at: minutes_ago(1),
        metadata: %{
          "dev_seed" => @perf_seed_key,
          "source_assignment_ids" => source_assignment_ids,
          "source_assignment_models" => source_assignment_models
        }
      })
      |> Repo.insert!()
    end)
  end

  defp seed_perf_quota_windows!(identities) do
    identities
    |> Enum.map(fn identity ->
      quota_attrs(
        identity,
        quota_window_spec("primary", 300, "account", 10_000, 9_250, "7", "fresh")
      )
    end)
    |> Enum.map(fn attrs ->
      attrs
      |> put_in([:metadata], %{"dev_seed" => @perf_seed_key})
      |> then(&(%AccountQuotaWindow{} |> AccountQuotaWindow.changeset(&1) |> Repo.insert!()))
    end)
  end

  defp seed_perf_circuit_states!(pool, assignments) do
    route_classes = ["proxy_http", "proxy_stream", "proxy_websocket"]

    assignments
    |> Enum.with_index()
    |> Enum.map(fn {assignment, index} ->
      route_class = Enum.at(route_classes, rem(index, length(route_classes)))

      %RoutingCircuitState{}
      |> RoutingCircuitState.changeset(%{
        pool_id: pool.id,
        api_key_id: nil,
        pool_upstream_assignment_id: assignment.id,
        upstream_identity_id: assignment.upstream_identity_id,
        model_identifier: "gpt-5.5",
        route_class: route_class,
        status: "closed",
        reason_code: nil,
        failure_count: 0,
        success_count: 3,
        closed_at: minutes_ago(1),
        last_success_at: minutes_ago(1),
        metadata: %{"dev_seed" => @perf_seed_key},
        created_at: now(),
        updated_at: now()
      })
      |> Repo.insert!()
    end)
  end

  defp seed_perf_sessions!(pool, api_key, assignments) do
    assignments
    |> Enum.take(3)
    |> Enum.with_index(1)
    |> Enum.map(fn {assignment, index} ->
      %CodexSession{
        pool_id: pool.id,
        api_key_id: api_key.id,
        session_key: "dev-perf-session-#{index}",
        conversation_key: "dev-perf-conversation-#{index}",
        pool_upstream_assignment_id: assignment.id,
        status: "active",
        created_at: minutes_ago(index + 5),
        updated_at: minutes_ago(index)
      }
      |> Repo.insert!()
    end)
  end

  defp seed_perf_metrics_token!(metrics_token) do
    settings = InstanceSettings.ensure_singleton!()
    attrs = InstanceSettings.put_metrics_bearer_token(%{}, metrics_token)
    {:ok, updated} = InstanceSettings.update_system_settings(settings, attrs)
    updated
  end

  defp write_perf_bootstrap!(%{} = result) do
    File.rm_rf!(@perf_bootstrap_dir)
    File.mkdir_p!(@perf_bootstrap_dir)
    File.chmod!(@perf_bootstrap_dir, 0o700)

    write_perf_summary!(result)
    write_perf_env!(result)
  end

  defp write_perf_summary!(%{pool: pool, api_key: api_key, assignments: assignments} = result) do
    summary = %{
      "pool_slug" => pool.slug,
      "api_key_prefix" => api_key.key_prefix,
      "upstream_count" => length(assignments),
      "http_hosts" => perf_hosts(assignments, ["base_url", "cluster_base_url"]),
      "websocket_hosts" => perf_hosts(assignments, ["websocket_url", "cluster_websocket_url"]),
      "metrics_token_present" => true,
      "created_at" => DateTime.to_iso8601(now()),
      "starter_rows" => result.starter_rows
    }

    File.write!(@perf_summary_path, CodexPooler.JSON.encode_to_iodata!(summary, pretty: true))
  end

  defp write_perf_env!(%{pool: pool, raw_api_key: raw_api_key, metrics_token: metrics_token}) do
    content =
      [
        "CODEX_POOLER_PERF_API_KEY=#{raw_api_key}",
        "CODEX_POOLER_PERF_POOL_SLUG=#{pool.slug}",
        "CODEX_POOLER_PERF_METRICS_TOKEN=#{metrics_token}",
        "CODEX_POOLER_PERF_ALLOW_HOSTS="
      ]
      |> Enum.join("\n")
      |> Kernel.<>("\n")

    File.write!(@perf_env_path, content)
    File.chmod!(@perf_env_path, 0o600)
  end

  defp perf_hosts(assignments, keys) do
    assignments
    |> Enum.flat_map(fn assignment ->
      Enum.flat_map(keys, &perf_host(assignment, &1))
    end)
    |> Enum.uniq()
    |> Enum.sort()
  end

  defp perf_host(assignment, key) do
    case URI.new(Map.get(assignment.metadata || %{}, key, "")) do
      {:ok, %URI{host: host}} when is_binary(host) -> [host]
      _uri -> []
    end
  end

  defp perf_endpoint_metadata(label) do
    %{
      "dev_seed" => @perf_seed_key,
      "base_url" => @perf_http_url,
      "websocket_url" => @perf_websocket_url,
      "cluster_base_url" => @perf_cluster_http_url,
      "cluster_websocket_url" => @perf_cluster_websocket_url,
      "perf_label" => label
    }
  end

  defp perf_upstream_label(index), do: "perf-upstream-#{pad2(index)}"

  defp pad2(index) do
    index
    |> Integer.to_string()
    |> String.pad_leading(2, "0")
  end

  defp generate_bootstrap_secret(label) do
    bytes = :crypto.strong_rand_bytes(32) |> Base.url_encode64(padding: false)
    "dev-perf-#{label}-#{bytes}"
  end

  defp quota_window_spec(
         window_kind,
         window_minutes,
         quota_key,
         active_limit,
         credits,
         used_percent,
         freshness_state
       ) do
    %{
      window_kind: window_kind,
      window_minutes: window_minutes,
      quota_key: quota_key,
      active_limit: active_limit,
      credits: credits,
      used_percent: used_percent,
      freshness_state: freshness_state
    }
  end

  @spec quota_attrs(UpstreamIdentity.t(), quota_window_spec(), keyword()) :: map()
  defp quota_attrs(identity, spec, extras \\ []) do
    timestamp = now()

    %{
      upstream_identity_id: identity.id,
      quota_key: spec.quota_key,
      window_kind: spec.window_kind,
      window_minutes: spec.window_minutes,
      active_limit: spec.active_limit,
      credits: spec.credits,
      reset_at: minutes_from_now(spec.window_minutes),
      used_percent: if(spec.used_percent, do: Decimal.new(spec.used_percent)),
      display_label: quota_display_label(spec.quota_key, extras),
      limit_name: quota_limit_name(spec.quota_key, extras),
      source: "codex_usage_api",
      source_precision: "observed",
      quota_scope: if(Keyword.get(extras, :model), do: "model", else: "account"),
      quota_family: spec.quota_key,
      model: Keyword.get(extras, :model),
      freshness_state: spec.freshness_state,
      last_sync_at: timestamp,
      observed_at: timestamp,
      merge_precedence: 50,
      metadata: %{"dev_seed" => @seed_key},
      created_at: timestamp,
      updated_at: timestamp
    }
  end

  defp quota_display_label("account", _extras), do: nil
  defp quota_display_label(_quota_key, extras), do: Keyword.get(extras, :display_label)

  defp quota_limit_name("account", _extras), do: nil
  defp quota_limit_name(quota_key, _extras), do: quota_key

  defp now, do: DateTime.utc_now() |> DateTime.truncate(:microsecond)
  defp minutes_ago(minutes), do: DateTime.add(now(), -minutes, :minute)
  defp minutes_from_now(minutes), do: DateTime.add(now(), minutes, :minute)
end
